version: '3.3'

services:
  api:
    build:
      context: ./services/api
      dockerfile: linux.prod.Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
    - ./.env.prod

  nginx:
    build: ./services/nginx
    ports:
      - 9000:80
    depends_on:
      - api
