version: '3.3'

services:
  api:
    build: ./services/api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/api/:/c/Users/Chayut/docker/flipcard/src/app"
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev