version: '3.3'

services:
  api:
    build:
      context: ./services/api
      dockerfile: windows.Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    # volumes:
    #   - ./services/api/:/c/Users/Chayut/docker/flipcard/src/app"
    ports:
      - 5000:5000
    env_file:
    - ./.env.prod